### ISSUE TITLE
Provide an example to use the library 

### ISSUE THREAD

**Issue by mostafa-raafat** [shinvey/redux-dynamic-modules-observable#1]
Could you please provide an example to use redux-dynamic-modules-observable ?

**Comment by shinvey** [comment]
> Could you please provide an example to use redux-dynamic-modules-observable ?

Hey mostafa,
This repo was merged into the original repo https://github.com/microsoft/redux-dynamic-modules
You can go there and explorer further.

**Comment by mostafa-raafat** [comment]
I already did that but i have 1 issue 
when i try to add any Epic i go throw infinity loop

```
import { postsReducer } from "./posts-reducer";
import { postsEpic } from "./posts-epic";

export function getPostsModule() {
    return {
        id: "posts",
        reducerMap: {
            postsState: postsReducer,
        },
        epics: [postsEpic]
    };
}
```

**Comment by shinvey** [comment]
> I already did that but i have 1 issue
> when i try to add any Epic i go throw infinity loop and postsLoaded action keeps firing
> 
> ```
> import { postsReducer } from "./posts-reducer";
> import { postsEpic } from "./posts-epic";
> 
> export function getPostsModule() {
>     return {
>         id: "posts",
>         reducerMap: {
>             postsState: postsReducer,
>         },
>         epics: [postsEpic]
>     };
> }
> 
> ---------------------------------------------------------------------------------------------------------------
> 
> import { mergeMap, map } from 'rxjs/operators';
> import { ajax } from 'rxjs/ajax';
> import { postsLoaded } from './posts-actions';
> 
> export const postsEpic = (action$) => action$.pipe(
>     mergeMap(action =>
>         ajax.getJSON('https://api.openweathermap.org/data/2.5/weather?q=Seattle&APPID=1362c34423375d167d694489b1c74080').pipe(
>             map(response => postsLoaded(response))
>         )
>     )
> )
> ```

getPostsModule looks okay, but the epic you may miss the [basic guide](https://redux-observable.js.org/docs/basics/Epics.html). Try add ofType() into your postsEpic
```js
export const postsEpic = (action$) => action$.pipe(
    ofType(‘weather’),
    mergeMap(action =>
        ajax.getJSON('https://api.openweathermap.org/data/2.5/weather?q=Seattle&APPID=1362c34423375d167d694489b1c74080').pipe(
            map(response => postsLoaded(response))
        )
    )
)
```
Then you could use `dispatch({ type: 'weather' })` to make it work. Have a try, it isn't tested myself but could solve the problem.

**Comment by mostafa-raafat** [comment]
The issue here Whenever you add postsEpic to epics array the postsEpic called right away,
so how can i specify action type with dispatch({ type: 'posts' })

Could you please take alook tothe repo to understand the problem ?

i wanted to have the same behavior as **redux-saga** but instead i used **redux-observable** 

https://github.com/mostafa-raafat/redux-dynamic-modules

**Comment by shinvey** [comment]
> The issue here Whenever you add postsEpic to epics array the postsEpic called right away,
> so how can i specify action type with dispatch({ type: 'posts' })
> 
> Could you please take alook tothe repo to understand the problem ?
> 
> i wanted to have the same behavior as **redux-saga** but instead i used **redux-observable**
> 
> https://github.com/mostafa-raafat/redux-dynamic-modules

Emm…… redux-observable is not the same as redux-saga. It's better to figure out what differences between them and maybe you should make time to do so. 

`ofType('weather')` is the same as `filter(action => action.type === 'weather')`. Why you encounter the infinity loop because there should be a filter `ofType` but you miss it.

The data stream should be like this: 
dispatch -> epic -> dispatch from the epic. Your postsLoaded returns an action -> reducer

How can I specify action type with dispatch({ type: 'posts' })?
Just name it whatever.  If go with parameters, try dispatch({ type: 'posts', payload: { param: 'value' } }). Then you can receive it in the epic. 
```js
    mergeMap(action =>
        ajax.getJSON('https://api.openweathermap.org/data/2.5/weather?q=Seattle&APPID=1362c34423375d167d694489b1c74080&param=' + action.payload.param).pipe(
            map(response => postsLoaded(response))
        )
    )
```

**Comment by shinvey** [comment]
> The issue here Whenever you add postsEpic to epics array the postsEpic called right away,
> so how can i specify action type with dispatch({ type: 'posts' })
> 
> Could you please take alook tothe repo to understand the problem ?
> 
> i wanted to have the same behavior as **redux-saga** but instead i used **redux-observable**
> 
> https://github.com/mostafa-raafat/redux-dynamic-modules

Emm…… redux-observable is not the same as redux-saga. It's better to figure out what differences between them and maybe you should make time to do so. 

`ofType('weather')` is the same as `filter(action => action.type === 'weather')`. Why you encounter the infinity loop because there should be a filter `ofType` but you miss it.

The data stream should be like this: 
dispatch -> epic -> dispatch from the epic. Your postsLoaded returns an action -> reducer

How can I specify action type with dispatch({ type: 'posts' })?
Just name it whatever.  If go with parameters, try dispatch({ type: 'posts', payload: { param: 'value' } }). Next you can receive it in the epic. 
```js
    mergeMap(action =>
        ajax.getJSON('https://api.openweathermap.org/data/2.5/weather?q=Seattle&APPID=1362c34423375d167d694489b1c74080&param=' + action.payload.param).pipe(
            map(response => postsLoaded(response))
        )
    )
```

**Comment by mostafa-raafat** [comment]
Redux-saga implementation by the way this is Microsoft example 
There is no ```filter(action => action.type === 'weather')``` because whenever you inject the **weather module** the sage will fire right away

```
import { weatherReducer } from "./weather-reducer";
import { weatherSaga } from "./weather-saga";

export function getWeatherModule() {
    return {
        // Unique id of the module
        id: "weather",
        // Maps the Store key to the reducer
        reducerMap: {
            weatherState: weatherReducer,
        },
        // This module uses redux-saga middleware
        // This property will be be used by the SagaExtension
        // to run sagas for the moduleD
        sagas: [weatherSaga],
    };
}
-----------------------------------------------------------------------------------------------------------------------------
import { call, put } from "redux-saga/effects";
import { weatherLoaded } from "./weather-actions";

export function* weatherSaga() {
    yield call(loadWeatherData);
}

function* loadWeatherData() {
    const url =
        "https://api.openweathermap.org/data/2.5/weather?q=Seattle&APPID=1362c34423375d167d694489b1c74080";

    const response = yield call(fetch, url);
    const json = yield call([response, response.json]);

    yield put(weatherLoaded(json));
}
```
Could you please take alook to the repo it's a fork from Microsoft example
https://github.com/mostafa-raafat/redux-dynamic-modules

**Comment by shinvey** [comment]
> Redux-saga implementation by the way this is Microsoft example
> There is no `filter(action => action.type === 'weather')` because whenever you inject the **weather module** the sage will fire right away
> 
> ```
> import { weatherReducer } from "./weather-reducer";
> import { weatherSaga } from "./weather-saga";
> 
> export function getWeatherModule() {
>     return {
>         // Unique id of the module
>         id: "weather",
>         // Maps the Store key to the reducer
>         reducerMap: {
>             weatherState: weatherReducer,
>         },
>         // This module uses redux-saga middleware
>         // This property will be be used by the SagaExtension
>         // to run sagas for the moduleD
>         sagas: [weatherSaga],
>     };
> }
> -----------------------------------------------------------------------------------------------------------------------------
> import { call, put } from "redux-saga/effects";
> import { weatherLoaded } from "./weather-actions";
> 
> export function* weatherSaga() {
>     yield call(loadWeatherData);
> }
> 
> function* loadWeatherData() {
>     const url =
>         "https://api.openweathermap.org/data/2.5/weather?q=Seattle&APPID=1362c34423375d167d694489b1c74080";
> 
>     const response = yield call(fetch, url);
>     const json = yield call([response, response.json]);
> 
>     yield put(weatherLoaded(json));
> }
> ```
> 
> Could you please take alook to the repo it's a fork from Microsoft example
> https://github.com/mostafa-raafat/redux-dynamic-modules

Maybe you should give it up to make Epic run like Saga, and follow the pattern from [this guide](https://redux-observable.js.org/docs/basics/Epics.html).
